code_execution_task:
  description: Execute the file saved as "generated_model.py". Use the FileExecutorTool for executing.
  expected_output: Verbatim output of the code execution
  agent: chief_button_pusher
  outputs:
    - name: execution_result
      description: Result of code execution

code_evaluation_task:
  description: >
    Evaluate the output of the code_execution_task in context of the file saved as "generated_model.py".
    As an expert at machine learning & programming, solve the issue and write fresh code.
    However, try to minimize major changes. You may use the tools at your disposal if required.  
    The entire file is python, so no need to markdown with ```python ... ``` in the output.
  agent: machine_learning_operations_engineer
  expected_output: Working python code saved as generated_model.py
  output_file: generated_model.py
  context:
    - code_execution_task
