dataset_acquisition_task:
  description: >
    Download the Kaggle dataset mentioned. You must:
    1. Download and properly save the dataset
    2. Confirm the download location and success
    3. Extract key information from the dataset documentation
    4. Identify evaluation metrics and potential use cases
  expected_output: >
    A complete dataset acquisition report including:
    - Download confirmation and file location
    - Dataset reference and key documentation points
    - Evaluation metrics
  agent: dataset_acquisition_specialist
