dataset_task:
  description: >
    Download the Kaggle dataset mentioned and provide key insights. You must:
    1. Download and properly save the dataset
    2. Confirm the download location and success
    3. Extract key information from the dataset documentation
    4. Identify evaluation metrics and potential use cases
  expected_output: >
    A complete dataset acquisition report including:
    - Download confirmation and file location
    - Dataset reference and key documentation points
    - Evaluation metrics
    - Initial assessment for usage
  agent: dataset_assessor

research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
