dataset_acquisition_task:
  description: >
    {topic} Download the Kaggle dataset mentioned. You must:
    1. Download and properly save the dataset
    2. Scan the downloaded folder for CSV files using the DirectoryReadTool and rename all files to snake case 
    3. Confirm the download location and success
  expected_output: >
    A complete dataset acquisition report including:
    - Download confirmation and absolute path of file location. You may use the PWDTool for this.
  agent: dataset_acquisition_specialist

ydata_download_task:
  description: >
    Analyze the provided dataset for the extracted columns using the YDataProfilingTool.
    Download and properly save the output JSON. Confirm the download location.
  expected_output: Absolute path of file location. No words before of after that.
  agent: dataset_acquisition_specialist

exploratory_data_analysis_task:
  description: >
    {json_filepath} Analyze the provided JSON and extract meaningful insights.
    User input: {user_input}
    ONLY focus on the attributes the user wants more information about.
    Generate a *very* concise natural language report.
  expected_output: >
    A *very* concise natural language report that:
    - Presents insights in clear, conversational language
    - Highlights the most important findings first
    - Explains technical concepts in accessible terms
    - Provides context for why certain insights matter
    - Includes specific examples from the data
  agent: exploratory_data_analyst

visualization_task:
  description: >
    {json_filepath} Analyze the provided JSON and create visualizations.
    User input: {user_input}
    ONLY focus on the attributes the user wants visualizations about.
    ALWAYS return ONLY the raw Plotly figure JSON.
    Do not include any other text, wrapper objects, or explanations - ONLY the figure JSON.
  expected_output: >
    A complete Plotly figure dictionary that can be directly converted to a Plotly figure object using go.Figure()
  agent: visualization_agent
