dataset_acquisition_task:
  description: >
    {topic} Download the Kaggle dataset mentioned. You must:
    1. Download and properly save the dataset
    2. Scan the downloaded folder for CSV files using the DirectoryReadTool and rename all files to snake case 
    3. Confirm the download location and success
  expected_output: >
    A complete dataset acquisition report including:
    - Download confirmation and absolute path of file location. You may use the PWDTool for this.
  agent: dataset_acquisition_specialist

column_selection_task:
  description: >
    Use the CsvPreview tool to read the first 5 rows, and extract all the column names.
    After that, use the HumanInTheLoopTool to get feedback on column selection.
  expected_output: A list of selected column names
  agent: human_feedback_specialist
  context:
    - dataset_acquisition_task

exploratory_data_analysis_task:
  description: >
    Analyze the provided dataset for the extracted columns using the YDataProfilingTool.
    Generate a comprehensive natural language report.
  expected_output: >
    A detailed natural language report that:
    - Presents insights in clear, conversational language
    - Highlights the most important findings first
    - Explains technical concepts in accessible terms
    - Provides context for why certain insights matter
    - Includes specific examples from the data
    - Makes actionable recommendations
  agent: exploratory_data_analyst
  context:
    - column_selection_task
