dataset_acquisition_task:
  description: >
    {topic} Download the Kaggle dataset mentioned. You must:
    1. Download and properly save the dataset
    2. Scan the downloaded folder for CSV files using the DirectoryReadTool and rename all files to snake case 
    3. Confirm the download location and success
  expected_output: >
    - Download confirmation and absolute path of file location. You may use the PWDTool for this.
  agent: dataset_acquisition_specialist

exploratory_data_analysis_task:
  description: >
    Analyze the provided dataset using the DataProfilingTool and generate a 
    comprehensive natural language report that covers:
    1. Dataset Overview
       - Total number of records and features
       - Data types distribution
       - Memory usage
    2. Data Quality Assessment
       - Missing values analysis
       - Duplicate records
       - Potential data inconsistencies
    3. Statistical Insights
       - Key statistics for numerical columns
       - Distribution patterns
       - Outlier detection
    4. Relationships and Patterns
       - Correlation analysis
       - Interesting relationships between variables
    5. Actionable Recommendations
       - Data quality improvements
       - Potential areas for deeper analysis
       - Data collection suggestions
  expected_output: >
    A detailed natural language report that:
    - Presents insights in clear, conversational language
    - Highlights the most important findings first
    - Explains technical concepts in accessible terms
    - Provides context for why certain insights matter
    - Includes specific examples from the data
    - Makes actionable recommendations
  agent: exploratory_data_analyst
  context:
    - dataset_acquisition_task
