code_execution_task:
  description: > 
    Execute the file saved as "generated_model.py". Use the FileExecutorTool for executing.
    Make sure that all caches are cleared and that each execution is fresh.
  expected_output: Verbatim output of the code execution. If it's an error then also share the root cause.
  agent: chief_button_pusher

code_evaluation_task:
  description: >
    Evaluate the output of the code_execution_task in context of the file saved as "generated_model.py".
    As an expert at machine learning & programming, solve the issue and write fresh code.
    The issue is in the generated_model code, not the site packages.
    Be sure sure to solve THAT specific issue. 
    You may use the tools at your disposal if required.  
    The entire file is python, so no need to markdown with ```python ... ``` in the output.
  agent: machine_learning_operations_engineer
  expected_output: Working python code saved as generated_model.py
  output_file: generated_model.py
  context:
    - code_execution_task
